#ENG OUT MESSAGES
# check running as root
LNG_ROOT_CHECK="\033[1A\033[K║ CHECKING ROOT...$(SPACES $CHR_SIZE-17 ║)\n$(BORDER ╚ ┘)\n"
LNG_ROOT_FAIL="\033[2A\033[K║ ACCESS DENIED$(SPACES $CHR_SIZE-14 ║)\n║     \e[1;36mRun this script as root [sudo].\e[1;31m$(SPACES $CHR_SIZE-36 ║)\n$(BORDER ╚ ┘)\e[0m\n"
LNG_ROOT_OK="\033[2A\033[K║ ROOT OK$(SPACES $CHR_SIZE-8 ║)\n$(BORDER ╚ ┘)\n"
# check if /boot/grub/themes exist
LNG_DIR_CHECK="\033[1A\033[K║ CHECKING BOOT THEME DIRECTORY...$(SPACES $CHR_SIZE-33 ║)\n$(BORDER ╚ ┘)\n"
LNG_DIR_FAIL="\033[2A\033[K║ BOOT THEME DIRECTORY CREATED$(SPACES $CHR_SIZE-30 ║)\n$(BORDER ╚ ┘)\n"
LNG_DIR_OK="\033[2A\033[K║ BOOT THEME DIRECTORY OK$(SPACES $CHR_SIZE-24 ║)\n$(BORDER ╚ ┘)\n"
# check current directory
LNG_CD_CHECK=
# clone repo 
LNG_GIT_CHECK="\033[1A\033[K║ UPDATING THEME FROM GITHUB...$(SPACES $CHR_SIZE-30 ║)\n$(BORDER ╚ ┘)\n"
LNG_GIT_FAIL="\033[2A\033[K║ FAILED TO UPDATE, INSTALL GIT OR DOWNLOAD THE REPOSITORY MANUALLY$(SPACES $CHR_SIZE-66 ║)\n$(BORDER ╚ ┘)\n"
LNG_GIT_OK="\033[2A\033[K║ THEME UPDATED$(SPACES $CHR_SIZE-14 ║)\n$(BORDER ╚ ┘)\n"
# copy theme to /boot/grub/themes
LNG_CP_CHECK="\033[1A\033[K║ COPYING NEW THEME...$(SPACES $CHR_SIZE-21 ║)\n$(BORDER ╚ ┘)\n"
LNG_CP_FAIL="\033[2A\033[K║ AN ERROR OCURRED WHILE COPYING THE THEME$(SPACES $CHR_SIZE-41 ║)\n$(BORDER ╚ ┘)\n"
LNG_CP_OK="\033[2A\033[K║ NEW THEME COPIED$(SPACES $CHR_SIZE-17 ║)\n$(BORDER ╚ ┘)\n"
# edit grub
LNG_EDIT_CHECK="\033[1A\033[K║ EDITING GRUB CONFIG...$(SPACES $CHR_SIZE-23 ║)\n$(BORDER ╚ ┘)\n"
LNG_EDIT_OK="\033[2A\033[K║ GRUB CONFIG MODIFIED$(SPACES $CHR_SIZE-21 ║)\n$(BORDER ╚ ┘)\n"
# update grub
LNG_UP_CHECK="\033[1A\033[K║ UPDATING THEME...$(SPACES $CHR_SIZE-18 ║)\n$(BORDER ╚ ┘)\n"
LNG_UP_FAIL="\033[2A\033[K║ FAILED TO UPDATE THEME$(SPACES $CHR_SIZE-23 ║)\n$(BORDER ╚ ┘)\n"
LNG_UP_OK="\033[2A\033[K║ GRUB THEME UPDATED$(SPACES $CHR_SIZE-19 ║)\n$(BORDER ╚ ┘)\n"
# grub error
LNG_NO_GRUB="\033[2A\033[K║ FAILED TO UPDATE THEME, PLEASE ENSURE GRUB IS INSTALLED CORRECTLY$(SPACES $CHR_SIZE-66 ║)\n$(BORDER ╚ ┘)\n"
# finish
LNG_FINISH="\033[1A\033[K║ THE THEME HAS BEEN INSTALLED SUCCESFULLY$(SPACES $CHR_SIZE-41 ║)\n║     \e[1;36mYou will now see it at the next reboot.\e[1;31m$(SPACES $CHR_SIZE-44 ║)\n$(BORDER ╚ ┘)\e[0m\n"